In [10]:
%matplotlib inline
import numpy as np
import pandas as pd

import viz # curriculum example visualizations

np.random.seed(29)
n_simulations = 100_000

### How likely is it that you roll doubles when rolling two dice?

#### Array for rolls

In [ ]:
n_dice = 2
outcomes = [1, 2, 3, 4, 5, 6]

In [34]:
n_simulations = nrows = 50

In [33]:
rolls = np.random.choice(outcomes, size=(n_simulations, n_dice))
rolls

array([[3, 5],
       [6, 6],
       [1, 2],
       [3, 5],
       [6, 5],
       [1, 3],
       [6, 3],
       [6, 6],
       [5, 6],
       [3, 4],
       [5, 2],
       [4, 2],
       [6, 4],
       [1, 4],
       [6, 6],
       [4, 5],
       [3, 1],
       [5, 3],
       [3, 5],
       [6, 2],
       [4, 1],
       [3, 4],
       [6, 4],
       [6, 2],
       [2, 4],
       [1, 4],
       [6, 4],
       [1, 4],
       [3, 1],
       [4, 4],
       [4, 2],
       [2, 4],
       [3, 6],
       [4, 6],
       [5, 2],
       [4, 2],
       [5, 5],
       [3, 3],
       [4, 2],
       [1, 3],
       [1, 1],
       [2, 1],
       [2, 4],
       [5, 1],
       [3, 6],
       [1, 1],
       [3, 6],
       [6, 4],
       [1, 6],
       [5, 4],
       [6, 6],
       [4, 4],
       [6, 3],
       [6, 4],
       [4, 4],
       [2, 5],
       [5, 3],
       [6, 4],
       [4, 6],
       [1, 3],
       [4, 4],
       [6, 3],
       [6, 4],
       [3, 1],
       [4, 5],
       [1, 2],
       [5,

In [35]:
rolls = pd.DataFrame(rolls)
rolls.head()

0  1
0  3  5
1  6  6
2  1  2
3  3  5
4  6  5

In [36]:
(rolls[0] == rolls[1]).mean() # When you roll double sample

0.18

#### If you flip 8 coins, what is the probability of getting exactly 3 heads?
- What is the probability of getting more than 3 heads?

In [15]:
n_coins = 8
outcomes = ['H', 'T']

In [74]:
trial_flips = np.random.choice(outcomes, size=(n_simulations, n_coins))

trial_flips

array([[2, 3, 5, 1, 2, 4, 2, 3],
       [2, 2, 3, 4, 5, 2, 6, 1],
       [5, 1, 3, 6, 2, 6, 4, 5],
       [2, 1, 4, 3, 6, 4, 2, 3],
       [2, 3, 1, 2, 5, 4, 3, 2],
       [4, 3, 3, 3, 4, 4, 4, 5],
       [2, 6, 5, 1, 4, 2, 6, 3],
       [2, 5, 1, 3, 2, 3, 3, 6],
       [2, 6, 5, 5, 4, 4, 3, 3],
       [2, 5, 1, 1, 1, 4, 4, 4]])

In [17]:
total_flips =(trial_flips == 'H').sum(axis=1)  #Possibility of the coinflip being Heads.
total_flips

array([4, 3, 6, ..., 5, 5, 5])

##### Landing on Heads more than 3 times

In [18]:
(total_flips > 3).mean()

0.63692

##### Landing on Heads exactly 3 times

In [19]:
(total_flips == 3).mean()

0.21889

There are approximitely 3 web development cohorts for every 1 data science cohort at Codeup. Assuming that Codeup randomly selects an alumni to put on a billboard, what are the odds that the two billboards I drive past both have data science students on them?

In [26]:
web_dev = 1
data_sci = 2
roll = np.random.choice([web_dev, data_sci], 1000*2, p=[.75, .25]).reshape(1000, 2)
roll

array([[1, 1],
       [1, 1],
       [1, 1],
       ...,
       [1, 1],
       [1, 2],
       [1, 2]])

In [27]:
double = roll >= 2
double

array([[False, False],
       [False, False],
       [False, False],
       ...,
       [False, False],
       [False,  True],
       [False,  True]])

In [28]:
(double.sum(axis=1) == 2 ).mean()*100

4.3

Codeup students buy, on average, 3 poptart packages with a standard deviation of 1.5 a day from the snack vending machine. If on monday the machine is restocked with 17 poptart packages, how likely is it that I will be able to buy some poptarts on Friday afternoon? (Remember, if you have mean and standard deviation, use the np.random.normal) You'll need to make a judgement call on how to handle some of your values

In [ ]:
n_trials = nrows = 100

codeup_students = 3
std_dev = 1.5
days = ['monday', 'tuesday', 'wednesday', 'thursday', 'friday']
calc = np.random.normal(codeup_students, std_dev, len(days)* n_trials).reshape(100,5)

In [ ]:
calc

In [ ]:
round(calc.sum(axis=1).mean(), 3) # mean of calc sum

Compare Heights

Men have an average height of 178 cm and standard deviation of 8cm.
Women have a mean of 170, sd = 6cm.
Since you have means and standard deviations, you can use np.random.normal to generate observations.
If a man and woman are chosen at random, what is the likelihood the woman is taller than the man?

In [ ]:
n_trials = 1000
men_avg = 178
men_stddev = 8
women_avg = 170
women_stddev =6

men_trial = np.random.normal(men_avg, men_stddev, n_trials).reshape(1000,1)
women_trial = np.random.normal(women_avg, women_stddev, n_trials).reshape(1000,1)

In [ ]:
men_trial

In [ ]:
women_trial

In [ ]:
trials = np.append(men_trial, women_trial,axis=1)

In [ ]:
trials

In [ ]:
calculation_men_women = men_trial<women_trial
calculation_men_women.sum(axis=0).mean()/len(calculation_men_women)*100

When installing anaconda on a student's computer, there's a 1 in 250 chance that the download is corrupted and the installation fails. What are the odds that after having 50 students download anaconda, no one has an installation issue? 100 students?

What is the probability that we observe an installation issue within the first 150 students that download anaconda?

In [82]:
anac = .004 # Probability of corruption
students = 50
outcomes = ['S', 'F']
n_students = 50
    


In [92]:
downloads = np.random.choice(outcomes, size = (n_simulations, n_students), p=[249/250, 1/250])
downloads

array([['S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S',
        'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S',
        'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S',
        'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S'],
       ['S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S',
        'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S',
        'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S',
        'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S'],
       ['S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S',
        'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S',
        'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S',
        'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S'],
       ['S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S',
        'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S',
     

In [93]:
(downloads =='S').sum(axis=1)

array([50, 50, 50, 50, 47, 50, 49, 50, 49, 50])

#### 50 Installs

In [94]:
((downloads == 'S').sum(axis=1) ==50).mean()

0.7

#### 100 installs

In [98]:
anac = .004 # Probability of corruption
students = 50
outcomes = ['S', 'F']
n_students = 100

downloads = np.random.choice(outcomes, size = (n_simulations, n_students), p=[249/250, 1/250])
downloads

array([['S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S',
        'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S',
        'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S',
        'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S',
        'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S',
        'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S',
        'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S',
        'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S'],
       ['S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S',
        'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S',
        'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S',
        'S', 'S', 'S', 'S', 'S', 'S', 'S', 'F', 'S', 'S', 'S', 'S', 'S',
        'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S',
        'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S

In [99]:
(downloads =='S').sum(axis=1)

array([100,  99,  98,  99, 100, 100,  97, 100, 100, 100])

In [100]:
((downloads == 'S').sum(axis=1) ==100).mean()

0.6

#### 150 installs at least 1 fail

In [101]:
outcomes = ['S', 'F']
n_students = 150

downloads = np.random.choice(outcomes, size = (n_simulations, n_students), p=[249/250, 1/250])
((downloads == 'S').sum(axis =1) <n_students).mean()

0.6

In [102]:
downloads = np.random.choice(outcomes, size = (n_simulations, n_students), p=[249/250, 1/250])
downloads

array([['S', 'S', 'S', ..., 'S', 'S', 'S'],
       ['S', 'S', 'S', ..., 'S', 'S', 'S'],
       ['S', 'S', 'S', ..., 'S', 'S', 'S'],
       ...,
       ['S', 'S', 'S', ..., 'S', 'S', 'S'],
       ['S', 'S', 'S', ..., 'S', 'S', 'S'],
       ['S', 'S', 'S', ..., 'S', 'S', 'S']], dtype='<U1')

In [106]:
((downloads == 'S').sum(axis=1) < n_students).mean()

0.1

## 7. There's a 70% chance on any given day that there will be at least one food truck at Travis Park. However, you haven't seen a food truck there in 3 days. How unlikely is this?

In [111]:
n_days = 3

In [112]:
trucks = np.random.choice([0, 1], size = (n_simulations, n_days), p = [0.3, 0.7])


In [113]:
trucks

array([[0, 1, 1],
       [1, 1, 1],
       [1, 1, 0],
       [1, 1, 1],
       [1, 1, 1],
       [0, 0, 0],
       [0, 0, 1],
       [0, 1, 1],
       [0, 1, 1],
       [1, 1, 1]])

In [116]:
(trucks.sum(axis = 1) == 0).mean()  #Sum of sample mean of trucks appearing each day.

0.1

### 8. If 23 people are in the same room, what are the odds that two of them share a birthday? What if it's 20 people? 40?

In [151]:
possible_outcomes = range(0, 365)
people = 23 

In [152]:
def cal_formula(possible_outcomes, people):
    calculation = np.random.choice(possible_outcomes, size =(n_simulations, people))
    return calculation
cal_formula(possible_outcomes, people)

array([[ 52, 271, 321, 136,  31,  10, 283, 355, 357, 330, 344, 316,  79,
        206, 360, 208, 289, 285, 323,  36, 254, 268, 185],
       [245, 334, 271,  19,  84, 292, 346, 248, 146, 105, 305,   8,  61,
         69,  91, 261,  62,   6,  35, 232, 328, 214, 248],
       [231, 195, 356,  20, 202,  22, 334,  46, 119, 159, 131, 333,  22,
        173, 298, 151, 134, 251, 165, 101, 107,  65,  43],
       [238, 299, 175, 209,  82, 301, 115, 361,  80,  95, 256, 194, 308,
        195, 192,  88, 109, 104, 232,  97, 319,  43, 140],
       [196, 244, 116, 246,   7, 146, 253, 258, 195, 318, 177, 103, 165,
        273,  43, 254, 264,  67,  40,  43,  86, 263,  97],
       [234, 269, 157,  24, 229, 292, 353, 133, 113, 317, 176, 199, 129,
         77, 343, 227, 241,  68,  64, 210,  49,  43, 201],
       [121, 209,  94, 336, 145, 362, 250, 344, 314, 126, 233, 101,  10,
        240, 116, 233, 153, 265, 107, 360, 308, 239, 246],
       [290,  98,  77,  94, 362, 146, 324,  10, 311,   2, 328, 344, 246,
   

In [153]:
calculation = pd.DataFrame(calculation) ## DataFrame of calculation
calculation.head()

0    1    2    3    4    5    6    7    8    9   ...   13   14   15   16  \
0  244  263  112  351  353  234  161  323  185  304  ...   47  284  147  121   
1  111  225  198   86    0  187  134  223  301  355  ...  248  181  147  135   
2  153   77  326  170  263   19  239   20  245   93  ...  210  191  244  316   
3  128  359  316  284   44   91  346  121   46   92  ...  138  284  348  119   
4  155  248  193  129  307  348   91  208  281  364  ...  111  255  190  348   

    17   18   19   20   21   22  
0   22  142  234   74  287  315  
1  191  116  316  144  127  313  
2  144  180   63  198  290  232  
3  312    7   42    8   12  292  
4  170   50  152  302  228  288  

[5 rows x 23 columns]

In [154]:
calculation.nunique(axis=1) # unique values of row total
(calculation.nunique(axis=1) <23).mean() # odds of 23 people having the same birthday in a room

0.6

In [155]:
people= 20
people_20 = cal_formula(possible_outcomes, people)
people_20 = pd.DataFrame(people_20)
people_20
(people_20.nunique(axis=1) == people).mean()

0.7

In [156]:
people= 40
people_40 = cal_formula(possible_outcomes, people)
people_40 = pd.DataFrame(people_40)
people_40

0    1    2    3    4    5    6    7    8    9   ...   30   31   32   33  \
0   56  112  210  303  121  361  117  106   72  322  ...   15  105  157   11   
1  241    2  227  294  117   88   50  322  337  141  ...  156  111   96  339   
2  184   93  338  318  275  106  104   47   59  212  ...  271   73  259  204   
3  321  355  336   53  270  216  131  253  185   31  ...  167   21   41  167   
4   74  147    4  249  268   58    3  333   63  150  ...  131   49  260   73   
5  113  169  253   10  182  352   27   61  100  317  ...   80  309   53  193   
6   44  339   54  236  291   70  236    6   95   30  ...  122  118  352  186   
7   71    8  142  168  280   45   81  125   37   55  ...   26  263  163  167   
8   56    1   68  302  102  346  274    1  362   27  ...  214  273  281  197   
9  213  296  156  356   40  240  119   16  161  147  ...  286   62  184  225   

    34   35   36   37   38   39  
0  304  265  129  357  252  155  
1  109  176   96  198   41  341  
2  110  332  319  209  204  223  
3  196   26  172  317  131  200  
4  110  202  308  201  103  103  
5  313  311  148  166   76   15  
6  306   91  199    8   72  339  
7   77   46  200  321  346  160  
8   15   83  182   52  352   96  
9  116  307   51   21  149   90  

[10 rows x 40 columns]

In [157]:
(people_40.nunique(axis=1) == people).mean()

0.2