In [10]:
%matplotlib inline
import numpy as np
import pandas as pd

import viz # curriculum example visualizations

np.random.seed(29)
n_simulations = 100_000

In [11]:
n_dice = 2
outcomes = [1, 2, 3, 4, 5, 6]

In [12]:
rolls = np.random.choice(outcomes, size=(n_simulations, n_dice))
rolls

array([[6, 4],
       [5, 6],
       [3, 1],
       ...,
       [5, 6],
       [5, 5],
       [6, 5]])

In [13]:
rolls = pd.DataFrame(rolls)
rolls.head()

0  1
0  6  4
1  5  6
2  3  1
3  1  2
4  2  1

In [14]:
(rolls[0] == rolls[1]).mean()

0.16645

In [ ]:
n_simulations = nrows = 10
n_dice_rolled = ncols = 2

a = np.random.choice([1, 2, 3, 4, 5, 6], nrows * 1).reshape(nrows, 1)
b = np.random.choice([1, 2, 3, 4, 5, 6], nrows * 1).reshape(nrows, 1)
a_b = np.random.choice([1, 2, 3, 4, 5, 6], nrows * ncols).reshape(nrows, ncols)

a_b

#### If you flip 8 coins, what is the probability of getting exactly 3 heads?
- What is the probability of getting more than 3 heads?

In [15]:
n_coins = 8
outcomes = ['H', 'T']

In [16]:
coinflips = np.random.choice(outcomes, size=(n_simulations, n_coins))

coinflips

array([['T', 'H', 'H', ..., 'T', 'H', 'H'],
       ['H', 'H', 'T', ..., 'H', 'T', 'T'],
       ['H', 'H', 'T', ..., 'H', 'H', 'H'],
       ...,
       ['T', 'H', 'H', ..., 'T', 'H', 'H'],
       ['T', 'H', 'H', ..., 'T', 'H', 'T'],
       ['H', 'H', 'H', ..., 'H', 'T', 'H']], dtype='<U1')

In [17]:
flips_sim =(coinflips == 'H').sum(axis=1)
flips_sim

array([4, 3, 6, ..., 5, 5, 5])

##### Landing on Heads more than 3 times

In [18]:
(flips_sim > 3).mean()

0.63692

##### Landing on Heads exactly 3 times

In [19]:
(flips_sim == 3).mean()

0.21889

If you flip 8 coins, what is the probability of getting exactly 3 heads? What is the probability of getting more than 3 heads?

In [ ]:
rng = np.random.default_rng()
h_t = rng.integers(2, size=8)
h_t

In [ ]:
round((h_t.sum(axis=0).mean()/8)*100)

There are approximitely 3 web development cohorts for every 1 data science cohort at Codeup. Assuming that Codeup randomly selects an alumni to put on a billboard, what are the odds that the two billboards I drive past both have data science students on them?

In [26]:
web_dev = 1
data_sci = 2
roll = np.random.choice([web_dev, data_sci], 1000*2, p=[.75, .25]).reshape(1000, 2)
roll

array([[1, 1],
       [1, 1],
       [1, 1],
       ...,
       [1, 1],
       [1, 2],
       [1, 2]])

In [27]:
double = roll >= 2
double

array([[False, False],
       [False, False],
       [False, False],
       ...,
       [False, False],
       [False,  True],
       [False,  True]])

In [28]:
(double.sum(axis=1) == 2 ).mean()*100

4.3

Codeup students buy, on average, 3 poptart packages with a standard deviation of 1.5 a day from the snack vending machine. If on monday the machine is restocked with 17 poptart packages, how likely is it that I will be able to buy some poptarts on Friday afternoon? (Remember, if you have mean and standard deviation, use the np.random.normal) You'll need to make a judgement call on how to handle some of your values

In [ ]:
n_trials = nrows = 100

codeup_students = 3
std_dev = 1.5
days = ['monday', 'tuesday', 'wednesday', 'thursday', 'friday']
calc = np.random.normal(codeup_students, std_dev, len(days)* n_trials).reshape(100,5)

In [ ]:
calc

In [ ]:
round(calc.sum(axis=1).mean(), 3) # mean of calc sum

Compare Heights

Men have an average height of 178 cm and standard deviation of 8cm.
Women have a mean of 170, sd = 6cm.
Since you have means and standard deviations, you can use np.random.normal to generate observations.
If a man and woman are chosen at random, what is the likelihood the woman is taller than the man?

In [ ]:
n_trials = 1000
men_avg = 178
men_stddev = 8
women_avg = 170
women_stddev =6

men_trial = np.random.normal(men_avg, men_stddev, n_trials).reshape(1000,1)
women_trial = np.random.normal(women_avg, women_stddev, n_trials).reshape(1000,1)

In [ ]:
men_trial

In [ ]:
women_trial

In [ ]:
trials = np.append(men_trial, women_trial,axis=1)

In [ ]:
trials

In [ ]:
calculation_men_women = men_trial<women_trial
calculation_men_women.sum(axis=0).mean()/len(calculation_men_women)*100

When installing anaconda on a student's computer, there's a 1 in 250 chance that the download is corrupted and the installation fails. What are the odds that after having 50 students download anaconda, no one has an installation issue? 100 students?

What is the probability that we observe an installation issue within the first 150 students that download anaconda?

In [ ]:
anac = .004 # Probability of corruption
students = 50
outcomes = ['S', 'F']
n_students = 50
    


In [ ]:
downloads = np.random.choice(outcomes, size = (n_simulations, n_students), p)
downloads

In [ ]:
(downloads =='S').sum(axis=1)

In [ ]:
((downloads = 'S').sum(axis=1) ==50).mean()

In [ ]:
outcomes = ['S', 'F']
n_students = 150

downloads = np.random.choice(outcomes, size = (n_simulations, n_students), p=)
((downloads = 'S').sum(axis =1) <n_students).mean()